apiVersion: v1
kind: Pod
metadata:
  name: pokemon-scanner-pod
spec:
  restartPolicy: Never
  containers:
    - name: pokemon-scanner
      image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
      imagePullPolicy: {{ .Values.image.pullPolicy }}
      command: ["/bin/sh", "-c", "echo 'Pod is ready for manual execution. Use kubectl exec -it pokemon-scanner-pod -- python pokemon_fetcher.py <pokemon_name>' && sleep infinity"]